### PR TITLE
Add Touchstone settings and requirements

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Fixes https://github.com/mitodl/odl-video-service/issues/6

#### What's this PR do?
- Adds/modifies variables in settings.py to enable Touchstone/Shibboleth support, but only if the 'USE_SHIBBOLETH' environment variable == 'True'

- Adds django-shibboleth-remoteuser to requirements.txt

#### Any background context you want to provide?
This is based on notes here: https://github.com/singingwolfboy/touchstone-notes#configure-django-with-shibboleth-headers

and was used for https://video.odl.mit.edu

### CODE REVIEW

**Comment by noisecapella** [comment]
Can you rebase please?

**Comment by noisecapella** [comment]
It looks like this PR now only adds one line to `.env.example`, is that correct?

**Comment by mbertrand** [comment]
Most of the changes were already incorporated into another PR, and the extra line on .env.example is optional.  Maybe this PR should just be closed?

**Comment by noisecapella** [comment]
I'm fine to merge it, just wanted to make sure it wasn't an oversight

**Pull request merged**
