### PR TITLE
Introduced mandatory settings

### LINKED ISSUE #72: Check for null/blank values for critical settings and raise an error
If settings required for upload/transcoding are blank, raise an exception on application startup.

### PR DESCRIPTION
**Pull request by giocalitri**
#### What are the relevant tickets?
closes #72

#### What's this PR do?
checks for mandatory settings at the app startup

#### How should this be manually tested?
remove at least one of the mandatory settings from the .env and the app should not start

### CODE REVIEW

**Comment by giocalitri** [comment]
@mbertrand I talked to George I removed the command from the docker file because we do not actually collect the static assets in that way.

**Comment by mbertrand** [comment]
There's no styling for the admin console unless I run collectstatic manually, is that okay?  Does the deployment script handle that?  Otherwise everything looks good to me.

**Comment by giocalitri** [comment]
oh.... that was unplanned.
I need another solution

**Comment by giocalitri** [comment]
@mbertrand  now it should work

**Pull request merged**
