### PR TITLE
Dorska/limit sidebar collections

### PR DESCRIPTION
**Pull request by adorsk**
#### What are the relevant tickets?
#523 

#### What's this PR do?
Limits to 10 collections in sidebar.

#### How should this be manually tested?
1. Ensure that you have > 10 collections.
2. Ensure that in `.env`,  your `PAGE_SIZE_COLLECTIONS` is > 10 . (remember to restart if you change the `.env` file)
3. Go to any page and open the side bar. You should see only 10 collections.

### CODE REVIEW

**Comment by mbertrand** [comment]
@adorsk can you rebase against master & resolve conflicts?

**Comment by adorsk** [comment]
@mbertrand 👍 rebased against master, ready for review again.

**Comment by adorsk** [comment]
@mbertrand removing `ENABLE_FRONTEND_PAGINATION` sounds good to me. Removed, ready again for review.
(I'll delete the other PR that had the pagination feature flag in it too)

**Comment by adorsk** [comment]
Closes #523 .

**Pull request merged**
