### PR TITLE
This adds back black background behind video

### PR DESCRIPTION
**Pull request by roberthouse54**
#### What's this PR do?
The black full-width background behind videos was lost as part of a recent change. This adds it back.

#### How should this be manually tested?
See that it looks ok.

### CODE REVIEW

**Comment by pdpinch** [comment]
Didn't we remove the black bars on purpose, in https://github.com/mitodl/odl-video-service/issues/119 ?

**Comment by roberthouse54** [comment]
I don't actually recall this. I didn't think we did. The black bars have always been a part of the design. I thought this was perhaps referencing something different. Matt told me we lost the black bars recently when he had to mess around with the sizing and layout of the multi-angle videos.

I am not clear what happened with that #119.

**Comment by noisecapella** [comment]
If I resize the browser window to shrink the video the black bars remain on the sides. Is that intentional?

screenshot from 2017-10-31 15-44-08

**Comment by roberthouse54** [comment]
No it is not. OK, let's put this on hold.

**Pull request closed without merging**
