### PR TITLE
More styling fixes

### LINKED ISSUE #185: Style Collection List Page
This page: https://video.odl.mit.edu/collections/ needs some design. 

Should be as simple as possible, possibly a simple implementation of https://material-components-web.appspot.com/list.html

- [ ] "Create New Collection" should be at the top of the list

### LINKED ISSUE #215: text changes to edit collection modal
- [ ] Change title to "Edit Collection"
- [ ] Change button labels to "Cancel" & "Save"

### PR DESCRIPTION
**Pull request by roberthouse54**
#### What are the relevant tickets?
closes #215, closes #185 

#### What's this PR do?
Various style fixes:

- makes footer less tall
- fixes text for Edit Video modal
- Styling for collections list page
- Responsive styling for collections list page, and collection detail page.
- various tweaks to video card styling
- various tweaks to page widths, margins, and breakpoints.

#### How should this be manually tested?
See that things work and look correct, and that the css is valid.

### CODE REVIEW

**Comment by pdpinch** [comment]
@roberthouse54 is this ready for review?

**Comment by pdpinch** [comment]
Also, will this close either #215 or #185?

If so, you should change the PR description to say: "closes #125" and/or "closes #185"

**Comment by noisecapella** [comment]
Everything looks good except the `20 Videos` thing

**Comment by roberthouse54** [comment]
Yeah this is ready to go. I removed  the "20 videos" thing and created a new issue for adding that, which Matt said he could do.

https://github.com/mitodl/odl-video-service/issues/241

**Pull request merged**
