### PR TITLE
fix embedded video not playing

### PR DESCRIPTION
**Pull request by tasawernawaz**
#### What are the relevant tickets?
#740 

#### How should this be manually tested?
Not sure, how can test this. At least tests should pass.

### CODE REVIEW

**Comment by pdpinch** [comment]
I don't want to slow down this PR at all, but I'm curious if there is something we should do to get this type of error to show up in Sentry. 

I see errors like https://sentry.io/share/issue/8ebe19ea8e04425584f6b6ef76a5ed79/ and https://sentry.io/share/issue/e964694727e9435490feb03b53447468/ but nothing related to Residential MITx

**Comment by tasawernawaz** [comment]
@pdpinch May I should have asked this question sometime earlier, but I was confuse what actually `Residential MITx` refers to?

**Comment by mbertrand** [comment]
@pdpinch @tasawernawaz  The error `VM606 www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://video.odl.mit.edu').` is not responsible for the lack of playability, it occurs even when the video does play on another browser and/or when `autoplay=true` is added to the iframe, making it playable in Chrome.  It does not seem to affect usability.

Raven.js is showing up in the stack trace, not sure why it isn't showing up in sentry but my guess is because the error is originating from the Youtube script, there is a plugin issue about it here: https://github.com/videojs/videojs-youtube/issues/67

**Comment by pdpinch** [comment]
Ok, if we can't get it into Sentry, that's OK. If this fixes the issue, let's merge it and move on. 

In terms of the fix -- will folks who have the current embed code need to update it?

**Comment by tasawernawaz** [comment]
@pdpinch  This will surely fix for the new embedded code, @mbertrand can you answer for the existing issue ?

**Comment by mbertrand** [comment]
@pdpinch @tasawernawaz Yes I think anyone using the old iframe code will need to add `allow="autoplay"` so that it will be playable in Chrome again.

**Pull request merged**
